name: Build java application

on: [push]

permissions:
  content: read
  package: write

jobs:
  build:
    name: Build & upload artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Build and test
        run: mvn -B package test --file java-app/pom.xml

      - uses: actions/upload-artifact@v4
        with:
          name: java-app-example
          path: java-app/target/*.jar
      
      - name: Deploy artifact on github
        run: mvn deploy --file java-app/pom.xml