name: Build java application

on: [push]

jobs:
  build:
    name: Build & upload artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Build with Maven
        run: mvn -B package --file java-app/pom.xml