name: Greetings comment on issue creation
  
on:
  issues:
    types: [opened]

jobs:
  greetings:
    name: Add greeting message on issue
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v3
        with:
          issue_message: Welcome !!! 🥳🚀🚀🚀