name: Report java code quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: .github/actions/code-quality-java
        with:
          working-directory: java-app

      - uses: actions/upload-artifact@v4
        with:
          name: java-app-example
          path: java-app/target/*.jar
      
      - name: Deploy artifact on github
        run: mvn deploy --file java-app/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}